Fixing a bug in s3-upload-bundle

diff --git a/nubis/bin/s3-upload-bundle b/nubis/bin/s3-upload-bundle
--- a/nubis/bin/s3-upload-bundle
+++ b/nubis/bin/s3-upload-bundle
@@ -88,11 +88,12 @@ for image in $image_parts ${manifest_path}; do
    # Some regions only provide eventual consistency, since the --acl option on 'aws s3' doesn't
    # support the AMI canned ACL we have to do it later, which gives us the opportunity to run
    # put-object-acl on a object that may have not reached full consistency. 
-   timer=60
+   timer=120
    plural="s"
-   until false; do
+   until aws s3 ls s3://${bucket}/${image} >/dev/null 2>&1; do
       if [[ ${timer} -lt 1 ]]; then
-         break
+         echo "Upload to S3 failed"
+         exit 1
       else
          if [[ ${timer} -eq 1 ]]; then
             plural=""
